___
# Ciência dos Dados - PROJETO 1

Gabriel Scodiero

## TÍTULO DO SEU PROJETO

___
## Introdução

Descreva aqui o que pretende analisar!

Capriche no português!! 
Se quiser pode utilizar pesquisas semelhantes publicadas em sites confiáveis!!

___
## Análise e Resultados

In [87]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [88]:
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
/Users/gabiuas

In [89]:
#Se usar o arquivo descompactado
#pd.read_csv('DOM2015.csv',sep=',')

#Se usar o arquivo compactado como está no dropbox púbico
#pd.read_csv('DOM2015csv.zip', compression='zip', header=0, sep=',', quotechar='"')

In [90]:
dados13 = pd.read_csv('DOM2013csv.zip', compression='zip', header=0, sep=',', quotechar='"')
dados14 = pd.read_csv('DOM2014csv.zip', compression='zip', header=0, sep=',', quotechar='"')
dados15 = pd.read_csv('DOM2015csv.zip', compression='zip', header=0, sep=',', quotechar='"')

In [91]:
df13= pd.DataFrame({"UF":dados13.UF})


#COLUNAS
df13['RU']=dados13.V4105
df13['Tv_cor']=dados13.V0226
df13['Tv_fina']=dados13.V02270
df13['Tv_tubo']=dados13.V02271
df13['tv_ass']=dados13.V02272
df13['dg_abert']=dados13.V02273
df13['tv_para']=dados13.V02274
df13['dvd']=dados13.V2027
df13['micro']=dados13.V0231
df13['tablet']=dados13.V02321
df13['internet']=dados13.V02322
df13['mes_domici']=dados13.V4614
df13['dom_per_capt']=dados13.V4622



#RESPOSTAS
df13.Tv_cor = df13.Tv_cor.astype('category')
df13.Tv_cor.cat.categories = ('Sim','Não')

df13.dvd = df13.dvd.astype('category')
df13.dvd.cat.categories = ('Sim','Não')

df13.tv_para = df13.tv_para.astype('category')
df13.tv_para.cat.categories = ('Sim','Não','NS')

df13.tv_ass = df13.tv_ass.astype('category')
df13.tv_ass.cat.categories = ('Sim','Não')

df13.dg_abert = df13.dg_abert.astype('category')
df13.dg_abert.cat.categories = ('Sim','Não','NS')

df13.micro = df13.micro.astype('category')
df13.micro.cat.categories = ('Sim','Não')

df13.tablet = df13.tablet.astype('category')
df13.tablet.cat.categories = ('Sim','Não')

df13.internet = df13.internet.astype('category')
df13.internet.cat.categories = ('Sim','Não')

df13.dom_per_capt = df13.dom_per_capt.astype('category')
df13.dom_per_capt.cat.categories = ('Zero','Zero - 1/4','1/4 - 1/2','1/2 - 1','1 - 2','2 - 3','3 - 5','5+','SD')


#EXIGÊNCIAS
df13[((df13.UF==31)|(df13.UF==32)|(df13.UF==33)|(df13.UF==35))&(df13.mes_domici>1000)].sort_values(by='mes_domici').head(10).dropna()
#dados.sort_values(by="EDUCACAO").head()

#df13.iloc[0:11,[0,1,2,5,6,7,8,9,10,11,13]]

df13L=df13.iloc[:,[0,1,2,5,6,7,8,9,10,11,13]]
df13T=df13.iloc[:,[12]]
df13Tv=df13.iloc[:,[3,4]]


df13[((df13.UF==31)|(df13.UF==32)|(df13.UF==33)|(df13.UF==35))&(df13.mes_domici>1000)].sort_values(by='mes_domici').head(10).dropna()

,UF,RU,Tv_cor,Tv_fina,Tv_tubo,tv_ass,dg_abert,tv_para,dvd,micro,tablet,internet,mes_domici,dom_per_capt
87997,33,1,Sim,1.0,0.0,Sim,Sim,Sim,Sim,Sim,Não,Sim,1001.0,1 - 2
108318,35,1,Sim,1.0,0.0,Não,Não,Sim,Sim,Sim,Não,Sim,1002.0,1/4 - 1/2
82052,33,1,Sim,0.0,1.0,Não,Não,Sim,Sim,Não,Não,Não,1002.0,1/4 - 1/2
72525,31,1,Sim,0.0,2.0,Não,Não,Não,Sim,Não,Não,Não,1002.0,1/4 - 1/2
103530,35,1,Sim,1.0,1.0,Não,Não,Não,Não,Sim,Não,Não,1002.0,1/2 - 1
70114,31,8,Sim,1.0,1.0,Sim,Sim,Não,Sim,Não,Não,Não,1002.0,1/4 - 1/2
81844,33,1,Sim,0.0,1.0,Não,Não,Não,Sim,Não,Não,Sim,1003.0,1/4 - 1/2
106484,35,1,Sim,0.0,1.0,Não,Não,Não,Não,Não,Não,Não,1004.0,1/4 - 1/2
74608,31,1,Sim,0.0,1.0,Não,Não,Sim,Sim,Não,Não,Não,1004.0,1/4 - 1/2
100107,35,1,Sim,1.0,0.0,Não,Sim,Sim,Sim,Sim,Não,Não,1004.0,1/4 - 1/2

In [92]:
#df13L[((df13L.UF==31)|(df13L.UF==32)|(df13L.UF==33)|(df13L.UF==35))].sort_values(by='UF').head(10).dropna()

In [93]:
#df13T[(df13.mes_domici>1000)].sort_values(by='mes_domici').head(10).dropna()

In [95]:
df14= pd.DataFrame({"UF":dados14.UF})


#COLUNAS
df14['RU']=dados14.V4105
df14['Tv_cor']=dados14.V0226
df14['Tv_fina']=dados14.V02270
df14['Tv_tubo']=dados14.V02271
df14['tv_ass']=dados14.V02272
df14['dg_abert']=dados14.V02273
df14['tv_para']=dados14.V02274
df14['dvd']=dados14.V2027
df14['micro']=dados14.V0231
df14['tablet']=dados14.V02321
df14['internet']=dados14.V02322
df14['mes_domici']=dados14.V4614
df14['dom_per_capt']=dados14.V4622



#RESPOSTAS
df14.Tv_cor = df14.Tv_cor.astype('category')
df14.Tv_cor.cat.categories = ('Sim','Não')

df14.dvd = df14.dvd.astype('category')
df14.dvd.cat.categories = ('Sim','Não')

df14.tv_para = df14.tv_para.astype('category')
df14.tv_para.cat.categories = ('Sim','Não','NS')

df14.tv_ass = df14.tv_ass.astype('category')
df14.tv_ass.cat.categories = ('Sim','Não')

df14.dg_abert = df14.dg_abert.astype('category')
df14.dg_abert.cat.categories = ('Sim','Não','NS')

df14.micro = df14.micro.astype('category')
df14.micro.cat.categories = ('Sim','Não')

df14.tablet = df14.tablet.astype('category')
df14.tablet.cat.categories = ('Sim','Não')

df14.internet = df14.internet.astype('category')
df14.internet.cat.categories = ('Sim','Não')

df14.dom_per_capt = df14.dom_per_capt.astype('category')
df14.dom_per_capt.cat.categories = ('Zero','Zero - 1/4','1/4 - 1/2','1/2 - 1','1 - 2','2 - 3','3 - 5','5+','SD')


#EXIGÊNCIAS
df14[((df14.UF==31)|(df14.UF==32)|(df14.UF==33)|(df14.UF==35))&(df14.mes_domici>1000)].sort_values(by='mes_domici').head(10).dropna()
#dados.sort_values(by="EDUCACAO").head()

#df13.iloc[0:11,[0,1,2,5,6,7,8,9,10,11,13]]

df14L=df14.iloc[:,[0,1,2,5,6,7,8,9,10,11,13]]
df14T=df14.iloc[:,[12]]
df14Tv=df14.iloc[:,[3,4]]


df14[((df14.UF==31)|(df14.UF==32)|(df14.UF==33)|(df14.UF==35))&(df14.mes_domici>1000)].sort_values(by='mes_domici').head(10).dropna()

,UF,RU,Tv_cor,Tv_fina,Tv_tubo,tv_ass,dg_abert,tv_para,dvd,micro,tablet,internet,mes_domici,dom_per_capt
76267,31,1,Sim,0.0,2.0,Não,Não,Sim,Sim,Não,Não,Sim,1002.0,1/4 - 1/2
95932,35,8,Sim,1.0,1.0,Sim,Não,Não,Sim,Não,Não,Não,1002.0,1/4 - 1/2
82257,33,1,Sim,1.0,0.0,Não,Não,Não,Sim,Não,Não,Não,1002.0,1/4 - 1/2
107552,35,1,Sim,0.0,1.0,Não,Não,Não,Sim,Não,Não,Não,1003.0,1 - 2
70689,31,8,Sim,0.0,1.0,Não,Não,Sim,Não,Não,Não,Não,1004.0,1/4 - 1/2
108969,35,1,Sim,0.0,1.0,Não,Não,Não,Não,Não,Não,Não,1004.0,1 - 2
92392,33,1,Sim,1.0,0.0,Não,Sim,Não,Não,Não,Não,Não,1004.0,1/4 - 1/2
65838,31,1,Sim,0.0,1.0,Não,Não,Não,Sim,Não,Não,Não,1004.0,1/4 - 1/2
75918,31,1,Sim,0.0,1.0,Não,Não,Não,Sim,Não,Não,Sim,1005.0,1/4 - 1/2

In [96]:
df15= pd.DataFrame({"UF":dados15.UF})


#COLUNAS
df15['RU']=dados15.V4105
df15['Tv_cor']=dados15.V0226
df15['Tv_fina']=dados15.V02270
df15['Tv_tubo']=dados15.V02271
df15['tv_ass']=dados15.V02272
df15['dg_abert']=dados15.V02273
df15['tv_para']=dados15.V02274
df15['dvd']=dados15.V2027
df15['micro']=dados15.V0231
df15['tablet']=dados15.V02321
df15['internet']=dados15.V02322
df15['mes_domici']=dados15.V4614
df15['dom_per_capt']=dados15.V4622



#RESPOSTAS
df15.Tv_cor = df15.Tv_cor.astype('category')
df15.Tv_cor.cat.categories = ('Sim','Não')

df15.dvd = df15.dvd.astype('category')
df15.dvd.cat.categories = ('Sim','Não')

df15.tv_para = df15.tv_para.astype('category')
df15.tv_para.cat.categories = ('Sim','Não','NS')

df15.tv_ass = df15.tv_ass.astype('category')
df15.tv_ass.cat.categories = ('Sim','Não')

df15.dg_abert = df15.dg_abert.astype('category')
df15.dg_abert.cat.categories = ('Sim','Não','NS')

df15.micro = df15.micro.astype('category')
df15.micro.cat.categories = ('Sim','Não')

df15.tablet = df15.tablet.astype('category')
df15.tablet.cat.categories = ('Sim','Não')

df15.internet = df15.internet.astype('category')
df15.internet.cat.categories = ('Sim','Não')

df15.dom_per_capt = df15.dom_per_capt.astype('category')
df15.dom_per_capt.cat.categories = ('Zero','Zero - 1/4','1/4 - 1/2','1/2 - 1','1 - 2','2 - 3','3 - 5','5+','SD')


#EXIGÊNCIAS
df15[((df15.UF==31)|(df15.UF==32)|(df15.UF==33)|(df15.UF==35))&(df15.mes_domici>1000)].sort_values(by='mes_domici').head(10).dropna()
#dados.sort_values(by="EDUCACAO").head()

#df15.iloc[0:11,[0,1,2,5,6,7,8,9,10,11,13]]

df15L=df15.iloc[:,[0,1,2,5,6,7,8,9,10,11,13]]
df15T=df15.iloc[:,[12]]
df15Tv=df15.iloc[:,[3,4]]


df15[((df15.UF==31)|(df15.UF==32)|(df15.UF==33)|(df15.UF==35))&(df15.mes_domici>1000)].sort_values(by='mes_domici').head(10).dropna()

,UF,RU,Tv_cor,Tv_fina,Tv_tubo,tv_ass,dg_abert,tv_para,dvd,micro,tablet,internet,mes_domici,dom_per_capt
75070,31,1,Sim,1.0,0.0,Sim,Não,Sim,Sim,Sim,Não,Sim,1001.0,1/2 - 1
73009,31,1,Sim,0.0,2.0,Não,Não,Não,Sim,Não,Não,Sim,1001.0,1/2 - 1
67160,31,1,Sim,1.0,0.0,Não,Não,Não,Sim,Sim,Não,Sim,1002.0,1/2 - 1
78776,31,1,Sim,0.0,1.0,Não,Não,Sim,Não,Não,Não,Não,1002.0,1/4 - 1/2
96638,35,1,Sim,0.0,1.0,Não,Não,Não,Sim,Não,Não,Não,1002.0,1/2 - 1
75799,31,2,Sim,0.0,1.0,Não,Não,Não,Não,Não,Não,Não,1003.0,Zero - 1/4
71287,31,1,Sim,1.0,2.0,Sim,Sim,Não,Sim,Não,Não,Não,1005.0,Zero - 1/4
84297,33,1,Sim,1.0,1.0,Não,Sim,Não,Sim,Não,Não,Não,1005.0,1/4 - 1/2
86438,33,1,Sim,0.0,2.0,Não,Sim,Sim,Sim,Sim,Sim,Sim,1005.0,1/4 - 1/2
106314,35,1,Sim,0.0,2.0,Sim,Sim,Não,Não,Sim,Sim,Sim,1005.0,1/4 - 1/2


## Conclusão

Descreva aqui suas conclusões!